# Site settings
title: Crip.io
email: info@crip.io
description: Two Cripreneurs kicking ass in the digital world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://crip.io" # the base hostname & protocol for your site

# Permalink
permalink: /:title

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: "/page:num"

# Sass
sass:
  sass_dir: assets/_sass
  style: :compressed

# Exclude
exclude: ['node_modules/', 'package.json', 'Gulpfile.js', 'fabfile.py', 'fabfile.pyc']
