# Site settings
title: Crip.io
email: info@crip.io
description: Two crip's that are awesome
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://crip.io" # the base hostname & protocol for your site
twitter_username: cripreneurs
github_username:  crip

# Build settings
markdown: kramdown

# Exclude
exclude: ['node_modules/', 'package.json', 'Gulpfile.js', 'fabfile.py', 'fabfile.pyc']
